### ISSUE TITLE
Unable to get issuer cert locally

### ISSUE THREAD

**Issue by ptzbguenter** [TeamCodeStream/codestream#424] opened 2021-03-04 16:33 UTC
I encountered an issue when running behind a corporate firewall/proxy.
The initial load of CodeStream works but it seems like the publish stream is having some issues.
I don't see any updates automatically pushed to either Rider or VS Code, I have to reload the IDE or switch my Team back and forth to see any updates.

I constantly see this error message:
![image](https://user-images.githubusercontent.com/35847560/109995413-1d7b0300-7cc3-11eb-8d08-fd047e491111.png)

Looking at the logs using Rider's export logs function, I see this error message: 
```
2021-03-04 07:11:47,298 | INFO  | CodeStreamLanguageClient       | [2021-03-04 15:11:47:297] BROADCASTER: PUBNUB: PubNub network error: {"error":true,"operation":"PNHeartbeatOperation","errorData":{"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"},"category":"PNUnknownCategory"}
```

I have followed the [Proxy Support](https://docs.codestream.com/userguide/faq/proxy-support/) guide and enabled the appropriate flags.

![image](https://user-images.githubusercontent.com/35847560/109995943-98dcb480-7cc3-11eb-8905-e69b0d40b87b.png)

Is there any other setting I need to complete for publish updates to work?

**Comment by planteater** [comment] 2021-03-04 17:53
Thanks for the report @ptzbguenter! We're looking into this now, and I'll report back shortly.

**Comment by planteater** [comment] 2021-03-04 22:59
@ptzbguenter - Could I trouble you to send over a log file? In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post it here, you can send it to me directly at support@codestream.com. Thanks!

**Comment by cstryker** [comment] 2021-03-05 19:11
@ptzbguenter yes, you correctly identified in your logs that even though proxy support is on, we don't know your actual proxy URL. You attached an image in your email to my colleague that showed you have "Auto-detect proxy settings" on. Are you able to change that option to "Manual proxy configuration" and enter your proxy information in there? I'm hopeful that would solve the problem.

**Comment by ptzbguenter** [comment] 2021-03-09 16:10
Thanks @cstryker, I tried the manual configuration, but then the codestream didn't even load at all, just sat there spinning. It feels like the proxy is a windows integrated proxy, so then when configured manually, it gets confused. 😞 
I will email a log dump out to you for that.

I did get things to work, however, when digging into that `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` error. I think the pubnub service runs under node?
I ran across this SO post https://stackoverflow.com/a/49197727 where they indicated that I could grab the proxy certificate, and then set the `NODE_EXTRA_CA_CERTS` environment variable to the path to the proxy certificate.
That worked great for me and now I am receiving updates.
However, this is not an ideal solution since that certificate expires every two weeks so I'll have to manually grab a new certificate when that happens.

Is it possible to configure a whitelisted issuer or something along those lines?
I have verified that the "root" certificate is installed as a trusted root in windows.

**Comment by cstryker** [comment] 2021-03-09 16:43
@ptzbguenter thanks for the report. Glad you found a solution that works for you, even with the inconvenience of re-validating the proxy cert every two weeks. It is definitely on our roadmap to support whitelisting certificates as you suggest. Will let you know when we get that working.

**Comment by jimmyjayp** [comment] 2021-04-08 18:02
@ptzbguenter, if I understand correctly, you've added the proxy's certificate to your NODE_EXTRA_CA_CERTS path. While that will work, the path was actually intentioned to add the private CA bundle instead (although there's nothing wrong with adding the actual certificates). The persons/department who create and refresh the certificates your proxy uses have a CA bundle file (aka certificate chain, intermediary certs, etc...). This is what would typically be added to your computer's trust store (keychain on a mac, not sure what the app is called on windows) which would tell the computer to trust any certificates created by that CA. This is likely what was added to your computer's trust store so you don't have issues when web surfing. Contact them and ask them for the CA bundle / root & intermediary certs - expect more than one cert in the file - and save that to your computer and add that file to the NODE_EXTRA_CA_CERTS path.  I suggest you remove the proxy cert from that path as well so as to have an accurate test.

Assuming the CA bundle does not change often, you shouldn't have any issues when they renew the cert that resides on the proxy.  Let us know how it turns out.

**Comment by ptzbguenter** [comment] 2021-04-12 14:35
It seems as though the private CA bundle is already added to my trust store.
While it would probably work to add the CA bundle to the `NODE_EXTRA_CA_CERTS` path, my question here is why doesn't the node process already pick up and trust that certificate if it is in the trust store?
Why is the extra environment variable + file necessary?

In any case, I have as a test, grabbed the CA bundle (I think) and loaded that into the file.
I'll report back once I'm sure it's working past the intermediary expiry.

**Comment by aguycalledpete** [comment] 2021-04-13 08:35
I have also encountered this same issue when using the extension for VsCode. The initial load works but I do not receive live updates so if my coworkers make any updates, I need to close and reopen the IDE to receive and view the updates.
My employer also uses a proxy and I have also followed through the guide for enabling proxy support.

I am receiving the same yellow/orange warning message displaying at the bottom of the extension window and can see the same "UNABLE_TO_GET_ISSUER_CERT_LOCALLY" error code appearing in the 'output' panel shown in this screenshot.

![image](https://user-images.githubusercontent.com/66066155/114522061-e4776c00-9c3a-11eb-8d60-1d6652a6b30a.png)

I have been unable to use the work around with manually assigning a CA bundle which @ptzbguenter has found.

**Comment by jimmyjayp** [comment] 2021-04-15 13:38
@ptzbguenter, if you're referring to your operating system's trust store (eg. Keychain on the Mac), that won't have any effect here because the CodeStream LSP agent (a Node.js process) doesn't use your operating system's trust store. Sadly, operating system's don't really have a standard interface into their trust stores which can be added to more portable runtime environments like Node.js.  All that heavy lifting is done inside of browsers but as you're aware, browsers are built for their target operating systems.  Node.js apps, electron apps and the like are expected to provide a standard run-time environment across many OS's so a unified run-time distribution of the apps can work.  Node.js, in particular, has its own trust store containing the common public CA's (https://github.com/nodejs/node/blob/master/src/node_root_certs.h). The NODE_EXTRA_CA_CERTS path is its way of providing you a means to supplement to it.

Make sure you do not have any of the expired certs in your add-on files (NODE_EXTRA_CA_CERTS). My guess is an expired certificate would override a valid certificate authority's root and intermediate certs.

**Comment by jimmyjayp** [comment] 2021-04-15 13:49
@aguycalledpete can you clarify "manually assigning a CA bundle"?  Have you created a file containing your companiy's CA root and intermediary certs (bundle) and then added that file to the NODE_EXTRA_CA_CERTS path?  Are you confident that variable is defined in the environment in which VSCode is running?

**Comment by aguycalledpete** [comment] 2021-04-20 08:34
@jimmyjayp I was able to obtain the root CA and intermediary certs for my company's proxy and bundle them together into a single file. When trying to to add the file path to NODE_EXTRA_CA_CERTS I had trouble setting it in the correct environment. After some further research into the variable, I found that it could be set in the system properties of the computer, but even setting the variable and path to the bundle there does not seem to have worked for me since I was still receiving the same error message after re-launching VsCode.

**Comment by jimmyjayp** [comment] 2021-04-20 14:45
We recently added some code to the extension (it’s currently in our CI/CD pipeline) which will print the values of any NODE_* environment variables in the agent log. That will be included with our next extension release.  Once that’s out, you should be able to look at your codestream agent log in your IDE and make sure that the agent does, indeed, see the variable.

If it does, I’ll ask you to supply me a copy of the bundle file you’ve added to the path - you can remove the guts of the certificates if you don’t want to share them, I just need the headers/footers and the value of the NODE_ vars.

This will help me to try and reproduce.  I believe our next extension release is targeted for the end of this week.

JJ

**Comment by planteater** [comment] 2021-04-26 13:31
@aguycalledpete - The release (v11.0.4) that JJ mentioned above went out last week. You should be able to check for those NODE_* environment variables in the "CodeStream (Agent)" output now.

**Comment by aguycalledpete** [comment] 2021-04-28 09:58
Hi, thanks to the new extension update I was able to see that the environment variable is being picked up correctly in the logs.
`[2021-04-28 07:52:07:812] NODE_* environment variables:`
`[2021-04-28 07:52:07:813] NODE_EXTRA_CA_CERTS=C:\<folderpath>\bundle.pem`

It seems that there may also be additional error logging in place? I could now see a message showing the following error being logged: `BROADCASTER: PUBNUB: Server ping returned status error: true, assuming network hiccup`

Attached is a larger snippet of the logs which I hope may help.
![CodestreamLogs](https://user-images.githubusercontent.com/66066155/116385078-5db4b880-a810-11eb-85d5-32814bce336a.png)

**Comment by jimmyjayp** [comment] 2021-04-28 16:29
So I'm reaching out to PubNub for some detailed info but insofar as troubleshooting this further, do you have the ability to run an 'openssl' command on your client machine?  I want to see what certificate chain is coming back from the pubnub requests so we can determine if there are any mismatches with the certs in your bundle.pem file.

**Comment by jimmyjayp** [comment] 2021-04-28 17:36
One other point of clarification. Is your FW/outbound proxy transparent or did you explicitly set your IDE's config to point to it?

**Comment by aguycalledpete** [comment] 2021-05-05 14:20
I should have the ability to run 'openssl' commands on my machine, how might I go about checking the certificate chain used from the pubnub requests and I can analyse if there is a mismatch with certificates?

**Comment by jimmyjayp** [comment] 2021-05-05 17:34
We've been going back and forth with Pubnub on this.  I _believe_ (but am not sure), this command will show the chain:

openssl s_client -connect ps.pndsn.com:443

(You'll need to ctrl-C out of it after you get the data).

The PN engineers have asked about the proxy configuration.  Did you explicitly setup to use the proxy in your IDE ?  If so, what protocol scheme is it (http or https) is it?  If not can you confirm if it's transparent?  Finally can you ask your network guys if it's a SOCKS proxy ?

**Comment by aguycalledpete** [comment] 2021-05-12 07:35
Nope, I haven't changed any configurations or settings in VS Code since installation.

**Comment by aguycalledpete** [comment] 2021-06-03 14:04
Hi there, 

Just an update on my current situation.
It seems that now I am no longer receiving the previous PUBNUB error 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'.

However, I am still not receiving live updates, for example, when a member from my team assigns me to a Feedback Request.
In the CodeStream (Agent) logs I now see the following 2 errors recurring occasionally.
`BROADCASTER: PUBNUB: Server ping returned status error: true, assuming network hiccup`
`BROADCASTER: Ignoring network hiccup because subscriptions are already pending`

**Comment by cstryker** [comment] 2021-06-14 22:46
@aguycalledpete just so you know, we're working on a potential solution to your problem. This may involve a special "test" version of the extension that we may send to you to ask you to install. Should have something this week.

**Comment by cstryker** [comment] 2021-06-22 20:58
@aguycalledpete are you able to hit https://ps.pndsn.com/time/0 in your browser?

**Comment by aguycalledpete** [comment] 2021-07-06 10:43
Apoligies for the delay, I have only noticed recently that I seem to now be receiving the live updates in the form of notifications within VsCode which is expected with the CodeStream extension and I also do not see any errors logging in the console anymore :) I expect this is due to recent updates to the extension and I am happy to consider this closed now

**Closed** 2021-07-06 16:53 UTC
