### ISSUE TITLE
Slack Integration: No popups for read messages

### ISSUE THREAD

**Issue by jnjaeschke** [TeamCodeStream/CodeStream#47] opened 2019-04-05 08:37 UTC
I usually happen to have both the slack gui and vs code open on my desktop. When I react to messages in the Slack gui (read and answer them) and go back to VS Code, all unread messages are coming up as notifications even though I already read them. This could be quite annoying, especially if there are 10's or 100's of messages...

**Comment by planteater** [comment] 2019-04-05 19:46
@jnjaeschke - Thanks for the report. I haven't been able to reproduce this issue. Any actions I take in Slack, whether its a reaction or a reply, aren't triggering desktop notification from CodeStream in VS Code. I'm sure I'm not reproducing things correctly, so maybe you could give me some more detailed steps? Thanks!

**Comment by jnjaeschke** [comment] 2019-04-08 13:06
What information do you need? :)
 I open VS Code with Codestream extension enabled. I also have the Slack desktop app opened. When I chat with a collegue (in the Slack app) and I then go back to VS Code I see all messages from my collegue as notification (even though i read and responded to them in Slack).

**Comment by planteater** [comment] 2019-04-08 19:16
@jnjaeschke - First thing I would suggest trying is signing out of CodeStream (via the ellipses menu at the top-right of the CodeStream pane), and then authenticating again with Slack. Our best guess right now is that, for some reason, we're not getting the events to let us know that the messages in question have already been read on Slack.

If that doesn't fix the issue, can I trouble you for some log file info? First, go into your VS Code user settings and search for CodeStream. Then scroll down to the Trace Level setting and make sure it's set to "Debug". Reload VS Code, and then go into the Output view (Cmd + Shift + U on a Mac) and select "CodeStream (agent)" from the dropdown menu. You can either paste the output here, or email it to me at dave@codestream.com. Thanks!

**Comment by eli0shin** [comment] 2019-04-10 16:05
@planteater 
I love codestream but this bug has been driving me crazy. I often have 5+ vscode windows open and after a thread on slack have to manually click 'x' on every message I received (it always has 3 there so this has to be done sometimes 20 times to clear all the messages). This also must be done for every vscode window that I have open, I am constantly bombarded by day-old messages and have to spend a minute clearing each individually every time I switch vscode windows. This is even more annoying because the popup size is not standardized so i have to move my mouse a lot to fix all the 'x's.

IMO a far better user experience would be to rely on the slack notification messages and maybe only show slack notifications in code stream for codestream comments for the current working project. Slack read events in and of themselves can be very finicky and often don't reflect that messages have actually been read.

Well see how/if this gets fixed in the near future but I am afraid it is a breaking bug for me and if it persists will outweigh the benefits of codestream and probably end with me no longer using the product.

**Comment by planteater** [comment] 2019-04-10 16:33
@eli0shin - You can turn off CodeStream's desktop notifications within VS Code. Go to user settings in VSC, search for CodeStream, and the change the selection for Notifications to "None".

**Comment by planteater** [comment] 2019-04-19 19:35
@jnjaeschke - Just wanted to follow up to see if re-authenticating with Slack fixed the issue. If not, could I trouble you for those logs? Thanks!

**Closed** 2019-04-23 12:17 UTC
Labels: needs more info
