### ISSUE TITLE
Support korean language on commenting.

### ISSUE THREAD

**Issue by pycraft114** [TeamCodeStream/CodeStream#68] opened 2019-06-18 05:13 UTC
<img width="400" alt="스크린샷 2019-06-18 오후 2 12 29" src="https://user-images.githubusercontent.com/24728657/59654899-22d4a900-91d3-11e9-991e-071a11d57309.png">

Im using codestream plugin in webstorm. Seems like codestream does not support korean language. Seen above picture korean breaks when typed.

**Comment by planteater** [comment] 2019-06-18 14:53
This is a duplicate of https://github.com/TeamCodeStream/CodeStream/issues/56

We hope to have a fix shortly!

**Closed by planteater** 2019-06-18 14:53 UTC
Labels: bug, duplicate
