### ISSUE TITLE
Multiple organizations -> Not switching Jira

### ISSUE THREAD

**Issue by maxbeba** [TeamCodeStream/codestream#1450] opened 2023-05-01 07:25 UTC
I have two organizations. Both using jira for issues. I authorized for jira in both.
When switching the organization, the issues are always the same ones from the first organization, that I added.
So it seams, the jira config is bound to my account and not the current organization.

My scenario is pretty common if you have atlassian accounts in several companies.

- CodeStream Extension version:
- IDE Version: Webstorm 2023.1
- OS Version: MacOS 13.3.1

Steps to Reproduce:

1. Use a google account for everything related to atlassian
2. Create a jira site for Orga-A using your google account
3. Create some project in Orga-A and some tickets that you can easily identify as Orga-A issues
4. Create a second jira site for Orga-B using the same google account
5. Create some project in Orga-B and some tickets that you can easily identify as Orga-B issues
6. Log in to CodeStream on EU Servers
7. Create Orga-A in CodeStream
8. Connect Jira for Orga-A in CodeStream
9. Review the issues (should all be from Orga-A)
10. Create Orga B in CodeStream
11. Connect Jira for Orga-B in CodeStream
12. Review the issues (should all be from Orga-B -> But it shows those from Orga-A)

**Comment by planteater** [comment] 2023-09-12 16:51
Duplicate of https://github.com/TeamCodeStream/codestream/issues/732

**Closed by planteater** 2023-09-12 16:51 UTC
Labels: bug, duplicate
