### ISSUE TITLE
The user headimg  loading error,Text in the wrong line

### ISSUE THREAD

**Issue by Callanna** [TeamCodeStream/codestream#497] opened 2021-04-14 02:53 UTC
<img width="478" alt="image" src="https://user-images.githubusercontent.com/14858726/114647311-781a6c80-9d0f-11eb-9950-59d24fab666b.png">

**Comment by planteater** [comment] 2021-04-14 15:59
@Callanna - Is that the only place where the headshot image from gravatar isn't rendering, or is it broken everywhere? For example, check your profile. Or replies in a codemark/feedback request thread.

**Comment by Callanna** [comment] 2021-04-15 05:02
broken everywhere ! the gravatar isn't rendering,

**Comment by planteater** [comment] 2021-04-15 13:32
Gotcha. Looks like this is a duplicate of https://github.com/TeamCodeStream/codestream/issues/454

Can you follow that issue? I'll update things over there.

**Closed by planteater** 2021-04-15 13:32 UTC
Labels: duplicate
