### ISSUE TITLE
VSCode: CodeStream always opens a new editor group, doesn't open on VSCode load

### ISSUE THREAD

**Issue by AndrewMorsillo** [TeamCodeStream/CodeStream#114] opened 2019-09-17 21:24 UTC
When opening VSCode the CodeStream view does not reopen on it's own. The panel it was in is still there, but empty. 

Opening CodeStream from the command palette does not open it in the focused editor group but instead in a new editor group on the top right of the window. This is a minor thing but irritating because I have to do it on every editor start then fix the layout rearrangement it causes.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 3.0
 - OS + version: macOS 10.14.6
 - IDE + version: VSCode 1.38.1

**Comment by eamodio** [comment] 2019-09-17 21:32
We always try to open the CodeStream panel to the right side of the active editor (if possible -- and even this is very iffy because of the provided vscode apis), because we assume you are likely wanting to comment on that file. 

As for not loading at startup, I can't reproduce that -- it *should* remember the state when you restart (close/reopen) the IDE and re-open the CodeStream panel. Is the panel not opening at all, or just not in the same place?

**Comment by AndrewMorsillo** [comment] 2019-09-17 21:41
If I have the panel open, quit VSCode, then restart it, the CodeStream panel will not be open. There is an empty editor group where it was when I quit. I have to open it from the command palette again at which point it creates a new editor group, shrinking all the others including the empty one it was in from last session.

**Comment by eamodio** [comment] 2019-09-17 21:48
Hrm. Can you provide logs? https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

Thanks!

**Comment by AndrewMorsillo** [comment] 2019-09-18 14:21
Hmm, now CodeStream is reopening when I restart VSCode. Not sure why it wasn't happening previously. It still always opens in a new editor group instead of opening in the one it was in from last session. This is a bit annoying since it moves my layout around and I have to readjust it on every load.

**Comment by planteater** [comment] 2020-04-14 17:56
@AndrewMorsillo - This issue has been fixed in v7.0.2 of our extension.

**Closed by planteater** 2020-04-14 17:56 UTC
Labels: bug
