### ISSUE TITLE
Android Studio hangs after selecting first file for review

### ISSUE THREAD

**Issue by arnis71** [TeamCodeStream/codestream#1165] opened 2022-09-12 09:09 UTC
I was using the latest 12 version of code stream because the new layout looks awful but now it forces you to use the latest version which simply does not work. I am using MacBook Pro M1 Max and the repo is in enterprise gitlab account.

- IDE Version: Android Studio Chipmunk | 2021.2.1 Patch 2
- OS Version: macOS 12.5.1

Steps to Reproduce:

1. Install codestream
2. Open any file in the Pull request tree
3. File opens
4. No other file in the tree is clickable

Once one of the files in PR was viewed it is not possible to interact with other file in this PR. Please help me resolve this issue.

**Comment by marcelofarias** [comment] 2022-09-12 15:24
Thanks for the report @arnis71 ! Could I trouble you to send a log file? Reproduce the issue and then go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post it here, you can send it to me directly at [support@codestream.com](mailto:support@codestream.com). Thanks!

**Comment by marcelofarias** [comment] 2022-09-13 16:49
@arnis71 Unfortunately it's a little challenging to know what's going on without looking at those logs, since we can't reproduce it either. Are you aware of any public PRs where you can reproduce the issue? Or do you see anything unusual in the PR where the problem manifests?

**Comment by arnis71** [comment] 2022-09-16 07:38
@marcelofarias it is happening with any pr in our corporate repo. Our project is very big so maybe it can't handle it? Also this issue started since version 13 when the pr changes moved to the list of prs. On version 12 it worked fine. Maybe it is possible to somehow use version 12 until this is fixed?

**Comment by planteater** [comment] 2022-10-14 21:37
@arnis71 - We haven't been able to reproduce the issue, and are a little stuck without log files. Any chance you have another JetBrains IDE installed? Curious if it happens in one of the other IDEs, as Android Studio tends to be based on a slightly older version of IntelliJ.

**Comment by planteater** [comment] 2022-11-17 15:20
@arnis71 - I'm going to close this out for now, but if you're still seeing issues in the latest version of CodeStream, please reach out to me directly at codestream@newrelic.com and we'll dig into this more. Thanks

**Closed by planteater** 2022-11-17 15:20 UTC
