### ISSUE TITLE
FALSE: No Remote URL

### ISSUE THREAD

**Issue by mylostone** [TeamCodeStream/CodeStream#183] opened 2020-05-06 04:31 UTC
In intellij, codestream is saying:

This repo doesn’t have a remote URL configured. Your teammates won’t be able to see the codemark when viewing this source file. Learn more ...I follow the learn more link to see this advice:

From the command line, do a git remote -v to confirm whether or not you have a remote URL configured for this repository. If there is no remote URL, find out the correct URL and then specify the remote by doing a git remote add origin <remote URL>.

$ git remote -v 
origin  https://427.visualstudio.com/427%20Climate%20Data/_git/427%20Climate%20Data (fetch)
origin  https://427.visualstudio.com/427%20Climate%20Data/_git/427%20Climate%20Data (push)

$ git remote add origin 'https://427.visualstudio.com/427%20Climate%20Data/_git/427%20Climate%20Data'

fatal: remote origin already exists.

**Comment by planteater** [comment] 2020-05-06 14:05
Thanks for the report @mylostone. We'll get right on this!

**Comment by planteater** [comment] 2020-05-06 16:23
@mylostone - Unfortunately we haven't been able to reproduce the issue on our end, so a log file would be really helpful. Below are instructions for generating it. Feel free to send it to support@codestream.com if you'd prefer to not to post it here. Thanks!

- Go to Help > Debug Log Settings… in your IDE.
- In the "Custom Debug Log Configuration" dialog, add #com.codestream:trace and then click OK. (Note that you can remove this after you’ve sent us the log files so that logging isn't as verbose.)
- Restart the IDE.
- Reproduce the issue and then go to Help > Compress Logs and Show in Finder. This will open the finder where you should see a newly created zip file.

**Comment by planteater** [comment] 2020-05-15 12:35
@mylostone - Just wanted to follow up to see if you could send us that log file. Thanks!

**Comment by planteater** [comment] 2020-05-19 15:47
@mylostone - Since we can't reproduce this and can't investigate any further without a log file, I'm going to close this for now. That said, if you get the chance and can send a log file to support@codestream.com we'll dig into it asap. Thanks!

**Closed by planteater** 2020-05-19 15:47 UTC
Labels: bug
