### ISSUE TITLE
Codestream fonts are not readable in Intellij on Linux + 403 in connecting with newrelic one

### ISSUE THREAD

**Issue by vishalagrawal-jisr** [TeamCodeStream/codestream#784] opened 2021-12-02 09:41 UTC
Hi,
I'm using Rubymine 2020.3.1 on Linux. Codestream fonts are very blurry and 
also on adding New Relic User API Key and hitting "Connet to New Relic One" gives
GraphQL Error (Code: 403): 

Any help is appreciated, thanks.

![Screenshot from 2021-12-02 15-08-23](https://user-images.githubusercontent.com/69622004/144396737-dfab06a0-50cf-4af7-bdda-1016383038e8.png)

**Comment by planteater** [comment] 2021-12-02 11:40
@vishalagrawal-jisr - Thanks for reaching out. The display issue is a duplicate of the following issue. Unfortunately, that one is an issue with JetBrain's JCEF rendering on Linux and a bit out of our control.

As for the 403, if looks like your New Relic account is located in the EU data center. Apologies for the poor messaging here, but unfortunately the integration isn't yet available for EU accounts.

**Closed by planteater** 2021-12-02 11:40 UTC

**Comment by vishalagrawal-jisr** [comment] 2021-12-02 12:20
@planteater I tried the fix mentioned in that issue but even after unselecting "Use JCEF WebView" the display remains broken.
