### ISSUE TITLE
Github PR comments not showing up

### ISSUE THREAD

**Issue by spyderrsh** [TeamCodeStream/CodeStream#139] opened 2020-01-10 19:07 UTC
CodeStream isn't getting all the pull request comments from github. I've seen one, but none of the other comments are there. 1st group works, second group doesn't. No idea why.

![image](https://user-images.githubusercontent.com/3034414/72178946-447cc400-33a1-11ea-9206-f57f4afff52f.png)

![image](https://user-images.githubusercontent.com/3034414/72179056-79891680-33a1-11ea-971b-9179d4e804a2.png)

![image](https://user-images.githubusercontent.com/3034414/72179141-96254e80-33a1-11ea-927f-647d23fb7f2f.png)

![image](https://user-images.githubusercontent.com/3034414/72179227-bfde7580-33a1-11ea-8d2c-75eff3dd9f03.png)

Here's the logs:

[studio-logs-20200110-121338.zip](https://github.com/TeamCodeStream/CodeStream/files/4047470/studio-logs-20200110-121338.zip)

**Comment by planteater** [comment] 2020-01-13 16:48
Thanks for the report @spyderrsh. We're digging into this and will follow up as soon as we know more.

**Comment by planteater** [comment] 2020-01-15 16:56
@spyderrsh - Can you install v6.0 of the CodeStream extension, which just hit the marketplace, and let me know if that fixes the issue? Thanks!

**Comment by spyderrsh** [comment] 2020-01-15 17:33
I updated to v6.0--it's still not working:

![image](https://user-images.githubusercontent.com/3034414/72456429-e3c70000-3781-11ea-996b-0743087a6456.png)

I'm wondering if it matters--I'm on a fork doing a pull request upstream. Is that not handled? Is there some way to refresh or point it upstream?
[idea.log](https://github.com/TeamCodeStream/CodeStream/files/4066324/idea.log)

**Comment by marcelofarias** [comment] 2020-01-16 16:59
@spyderrsh by design, CodeStream only displays comments for merged pull requests. The pull request in the screenshot seems to be open. Is that the case? Are there any comments from merged PRs still missing?

**Comment by spyderrsh** [comment] 2020-01-16 18:20
I assumed that I could use CodeStream to pull the GitHub pull request comments to aid in resolving the code--that's the main functionality my team would be interested in. 

Also, it's still not working for merged PRs. I'm not seeing any comments now for either resolved or unresolved. Maybe I'm misunderstanding the GitHub PR functionality?

**Comment by marcelofarias** [comment] 2020-01-16 18:45
Thanks for the feedback, @spyderrsh. If possible, could you provide an example (just like you did on yesterday's post) of a missing comment from a merged PR along with logs?

**Comment by jpfeuffer** [comment] 2020-01-23 12:37
I also completely misunderstood the Github PR functionality and deinstalled Codestream as soon as I realized that it can only display merged PRs.
Rather useless for our team then.

**Comment by ppezaris** [comment] 2020-01-23 20:08
@jpfeuffer the motivation to only show comments from merged PRs is so that you don't see comments on branches that you don't have, or may never be merged.

Were you expecting to see comments from the PR of the branch you have checked out, or were you expecting to see comments from all PRs, even open ones on branches you were not on? Thanks.

**Comment by jpfeuffer** [comment] 2020-01-24 00:18
Ah ok so I will explain a bit more. Our use case would be to be able to check out PRs that are currently open to review them or with my own open PRs to be able to fix the parts of code that have requested changes from a review.

So yes, to be able to see the comments from a specific open PR branch (that I would check out then) would suffice in the beginning. Is this possible?

**Comment by ppezaris** [comment] 2020-01-24 01:24
> So yes, to be able to see the comments from a specific open PR branch (that I would check out then) would suffice in the beginning. Is this possible?

In a future release we will add the following ability:
if you are checked out to branch X, then when you look at a file in that repo, we will pull all of the PR comments from merged PRs (as we do today), plus all of the code comments for the open PR for branch X

if you want to see the PR comments for branch Y, you will have to checkout to branch Y, at which point CodeStream will show you PR comments from merged PRs plus code comments for the open PR for branch Y (but no longer comments for the open PR for branch X).

this is a straightforward change and can be done quickly.

in the future, we will also add the ability to interact with PRs more fully, but i wanted to check to make sure we were on the right track with this first step.

**Comment by spyderrsh** [comment] 2020-01-24 16:40
That's exactly the functionality that our team would be interested in as well.

**Comment by planteater** [comment] 2020-02-07 15:11
@spyderrsh @jpfeuffer - Comments from open PRs are now displayed, as long as you're on either the source or destination branch for the given PR.

**Closed by planteater** 2020-02-07 15:11 UTC
Labels: bug
