### ISSUE TITLE
CLion GitHub PR intergration: Checkout Branch Disabled

### ISSUE THREAD

**Issue by jpfeuffer** [TeamCodeStream/codestream#348] opened 2020-12-03 00:35 UTC
For any PR I get:

"Checkout Branch
Disabled: You don't have the XXX repo open in your IDE"

Although I clearly do. I even created most of the PRs through it. I am even on the branch that is the base for the PR.

**Comment by planteater** [comment] 2020-12-03 13:48
Thanks for the report @jpfeuffer! We'll get right on this.

**Comment by planteater** [comment] 2020-12-09 15:49
@jpfeuffer - We haven't been able to reproduce the issue on our end. Could I trouble you for a log file? Reproduce the issue and then go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If there are any other details about how you opened the project or have it set up that you think might be relevant, please include them as well. Thanks!

**Comment by jpfeuffer** [comment] 2020-12-10 12:26
I am not sure if there is something to reproduce, the icon is just always grey. It actually checks out the branch if I click on it but CodeStream is basically non-functional, since also the CodeStream drop-down selection is greyed out then.

**Comment by jpfeuffer** [comment] 2020-12-10 12:27
And after clicking around for a minute in the CodeStream sidebar, I already got a API rate exceeded warning.

**Comment by planteater** [comment] 2020-12-10 13:53
@jpfeuffer - We're currently working on that rate-limiting issues and should have an update out later this week. Unfortunately GitHub only gives each user a certain number of api calls per hour, so we're having to do some optimization work to make sure people don't hit that limit. For the moment, if you wait an hour and go back, you should be back in business. I'll update you as soon as our optimization work is released.

As for the original issue, it's sounding more like a general display issue than something specific to that checkout button. When you say the "CodeStream drop-down selection is greyed out", what exactly are you referring to? A log file would definitely help us debug this. Thanks!

**Comment by jpfeuffer** [comment] 2020-12-10 15:12
I meant the Dropdown menu when right-clicking in the Code Editor of CLion. I cannot click on CodeStream there and I don't see inline comments etc.
Can I send the log file to someone? But I cannot point out any "time" in the logs, since I don't know where the error would start.

**Comment by planteater** [comment] 2020-12-10 15:14
No worries @jpfeuffer! We'll dig through the logs. You can send the file to me directly at dave@codestream.com. Thanks!

**Comment by abhinav2600** [comment] 2020-12-12 16:01
@planteater If there is an option to set github personal access token, the limit is a lot higher.

**Comment by planteater** [comment] 2020-12-14 18:41
@jpfeuffer - Just wanted to follow up to see if we could get that log file. Thanks!

**Comment by abhinav2600** [comment] 2020-12-15 05:23
@planteater Do you need the idea.log file when codestream gets disabled because of hitting github limit? I can reproduce and help with that.

**Comment by jpfeuffer** [comment] 2020-12-15 11:51
I sent the logs for the initial issue, too. Not sure if the Rate limit issue is seen in there though.

**Comment by planteater** [comment] 2021-01-26 22:04
@jpfeuffer - I know it's been a while, but we haven't forgotten about you! Unfortunately, we haven't made any progress here, largely because we can't reproduce the issue. Aren't still experiencing the original problem with the latest version of CodeStream? If so, any chance I could trouble you for a screen recording showing us the issue? Thanks!

**Comment by planteater** [comment] 2021-02-08 15:27
@jpfeuffer - I'm going to go ahead and close this issue, but I'll follow up with you directly via email to see if we can try to get more information about this issue.

**Closed by planteater** 2021-02-08 15:27 UTC
Labels: bug

**Comment by rfst** [comment] 2021-11-10 11:28
Hey folks.

I'm facing the same problem on PHPStorm. 
Is there any settings I didn't set properly? 

![Screenshot 2021-11-10 at 12 25 26](https://user-images.githubusercontent.com/80040721/141105110-a544adfd-cfc2-4663-add8-aac965a254de.png)

**Comment by rfst** [comment] 2021-11-10 12:16
I just figured what was wrong. 
Below you find what I did, just in case it can help anyone else.

The problem was the name of the PHPStorm's project.

I was using PHPStorm 2021.2.1

1. Right click on the project name (the root folder of your project)
2. Go to `Refactor > Rename`
3. PHPStorm will ask if you want to rename the project or the directory. I chose "project".
4. Type in the name CodeStream spects it to be (the black part from the [image here](https://github.com/TeamCodeStream/codestream/issues/348#issuecomment-965040661))
5. Restart the IDE or maybe just re-open the project - I restarted it.

**Comment by jpfeuffer** [comment] 2021-11-10 14:44
Yes makes sense. My project folder is never called exactly like the git project.

**Comment by planteater** [comment] 2021-11-10 16:48
@rfst - It's very surprising that that change did the trick for you, as the project name isn't really used by CodeStream at all. Our repo matching is based on remote URL and commit hashes. If you run into this again, grab me a log file so we can dig into it. In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. Actually, your logs should go back far enough, before you did the rename, for us to see what was going on. So go ahead and grab them if you don't mind. If you don't want to post them here you can send them to me at support@codestream.com. Thanks
