### ISSUE TITLE
Stuck loading in PHPStorm

### ISSUE THREAD

**Issue by marijnbent** [TeamCodeStream/codestream#398] opened 2021-02-10 11:06 UTC
I have already reinstalled it, but the plugin is stuck on the loading screen.

On the latest PHPStorm

![loading](https://user-images.githubusercontent.com/11903095/107502012-6ba35780-6b98-11eb-9080-281a8ff28851.gif)

**Comment by planteater** [comment] 2021-02-10 12:12
Thanks for the report @marijnbent. In PHPStorm, try selection "CodeStream: sign out" from the IDE's actions list, and then sign back in. Let me know if that does the trick.

If not, a log file would be great. Go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can send the file to me at support@codestream.com if you'd prefer not to post it here. Thanks!

**Comment by marijnbent** [comment] 2021-02-11 09:06
@planteater Thanks for the suggestion. I tried the logout action, but nothing changed after unfortunately. I have sent an email containing the zip!

**Comment by chebeto** [comment] 2021-02-28 05:26
Same problem here! :(

**Comment by planteater** [comment] 2021-02-28 16:05
@chebeto - Thanks for letting us know. We hope to have this resolved in the coming days, but a log file from you as well would be helpful. See my earlier reply for instructions. Thanks!

**Comment by planteater** [comment] 2021-03-02 17:28
@chebeto - The URL below has a pre-release version of our extension that might allow us to get a clearer picture of what is going on here.

https://www.dropbox.com/s/bieequju3pgxusp/codestream-jb-10.6.2%2B3610.zip?dl=0

Once you've downloaded the file, you can install it by going to Preferences/Settings > Plugins and then select "Install Plugin from Disk" from the gear menu at the top-right.

Once you've installed the extension, restarted, and you get the CodeStream loading spinner again, look for a new action in IntelliJ called "CodeStream: Open webview dev tools". Select that and let us know if you see any errors in the dev tools console. Thanks!

**Comment by chebeto** [comment] 2021-03-02 20:21
> @chebeto - The URL below has a pre-release version of our extension that might allow us to get a clearer picture of what is going on here.
> 
> https://www.dropbox.com/s/bieequju3pgxusp/codestream-jb-10.6.2%2B3610.zip?dl=0
> 
> Once you've downloaded the file, you can install it by going to Preferences/Settings > Plugins and then select "Install Plugin from Disk" from the gear menu at the top-right.
> 
> Once you've installed the extension, restarted, and you get the CodeStream loading spinner again, look for a new action in IntelliJ called "CodeStream: Open webview dev tools". Select that and let us know if you see any errors in the dev tools console. Thanks!

Uncaught TypeError: window.cefQuery_85467128_1 is not a function
    at Object.postMessage (webview.html:5)
    at webview.html:13

[Link to Image](https://imgur.com/a/a6kIr8D)

**Comment by marijnbent** [comment] 2021-03-02 20:25
Same here:
```
Uncaught TypeError: window.cefQuery_514623699_1 is not a function
    at Object.postMessage (webview.html:5)
    at webview.html:13
```

**Comment by planteater** [comment] 2021-03-02 23:50
@marijnbent @chebeto - Could I trouble you to install the version of the CodeStream extension from the URL below, and let us know if it fixes the issue? Thanks!

https://www.dropbox.com/s/advswi4i9mzga8c/codestream-jb-10.6.2%2B3621.zip?dl=0

**Comment by chebeto** [comment] 2021-03-03 03:44
Hi @planteater , just install the version B3621 and the problem continues. Same error in console.

**Comment by marcelofarias** [comment] 2021-03-03 03:51
Hi @chebeto, thanks for checking. 2 questions:

1) If you run the "CodeStream: Reload webview" action (Cmd + Shift + A on Mac), does it eventually work? Could you try it a few times?
2) Could you share your IDE logs as described above to support@codestream.com ?

Thanks!

**Comment by chebeto** [comment] 2021-03-03 04:18
> Hi @chebeto, thanks for checking. 2 questions:
> 
> 1. If you run the "CodeStream: Reload webview" action (Cmd + Shift + A on Mac), does it eventually work? Could you try it a few times?
> 2. Could you share your IDE logs as described above to [support@codestream.com](mailto:support@codestream.com) ?
> 
> Thanks!

1.- I tried 10 times without success. I even signed out. The console logs the same error.

2.- Done, I just sent the log to the support email

**Comment by marcelofarias** [comment] 2021-03-10 19:04
Hi @marijnbent and @chebeto! Just wanted to touch bases and let you know I'm still investigating the issue. The PHP Storm logs you both provided indicate version PS-203.6682.180, so I wanted to ask if the problem is still occurring on newer versions.

Thanks!

**Comment by chebeto** [comment] 2021-03-10 19:10
> Hi @marijnbent and @chebeto! Just wanted to touch bases and let you know I'm still investigating the issue. The PHP Storm logs you both provided indicate version PS-203.6682.180, so I wanted to ask if the problem is still occurring on newer versions.
> 
> Thanks!

I just checked the application for updates and there is nothing new. It remains the same version since December 30

**Comment by marcelofarias** [comment] 2021-03-10 20:55
@chebeto Looks like there's at least one stable version after that: https://blog.jetbrains.com/phpstorm/2021/01/phpstorm-2020-3-2-is-released
Would you be able to try it?

**Comment by chebeto** [comment] 2021-03-10 21:05
> @chebeto Looks like there's at least one stable version after that: https://blog.jetbrains.com/phpstorm/2021/01/phpstorm-2020-3-2-is-released
> Would you be able to try it?

It works! 
![capture 2021-03-10 at 15 04 01](https://user-images.githubusercontent.com/651245/110697437-fa17f280-81b1-11eb-90bb-19d39ae58360.png)

**Comment by marcelofarias** [comment] 2021-03-10 21:08
@chebeto you would not believe how happy I am now! @marijnbent could you upgrade and give it a try as well?

**Closed by marcelofarias** 2021-03-10 21:08 UTC
Labels: bug

**Comment by marijnbent** [comment] 2021-03-11 10:33
Unfortunately, I still have the same error. Tried to reinstall Codestream, run the webview reload action and the signout action, but no success. 

![image](https://user-images.githubusercontent.com/11903095/110773993-9e0aa800-825d-11eb-8e60-e4be02644410.png)

**Comment by marcelofarias** [comment] 2021-03-11 14:13
@marijnbent could you confirm what version are you running? (you can copy it from PHP Storm > About)

**Comment by marijnbent** [comment] 2021-03-12 10:17
![image](https://user-images.githubusercontent.com/11903095/110926287-19cb2a00-831c-11eb-9edd-4ca8ec0f8b94.png)

**Comment by marijnbent** [comment] 2021-03-12 11:16
Not sure what the problem was, but PHPStorm was acting weird with updates (after clicking the update action and restarting, it never did), so after reinstalling PHPStorm it miraculously works!

Thanks for all the work @marcelofarias!

![image](https://user-images.githubusercontent.com/11903095/110933174-53a02e80-8324-11eb-80a3-14f936f62a18.png)
