### ISSUE TITLE
Cygwin git support

### ISSUE THREAD

**Issue by dailytabs** [TeamCodeStream/CodeStream#57] opened 2019-05-15 16:29 UTC
**Describe the bug**
In IntelliJ, when attempting to "Add Comment" I get the "No Remote URL" error message.

`git remote -v` shows remote is setup correctly for both repositories in the project.

This project has 2 git repositories. Both have remotes setup properly. They are also properly defined in IntelliJ's settings (Settings > Version Control).
![image](https://user-images.githubusercontent.com/1219653/57788691-8451b580-7705-11e9-80ef-bf45f7a46dfa.png)

**System Info:**
 - Plugin 1.0.1+1
 - Win 10 Home 1809
 - IntelliJ 2019.1.1

**Log Files**
I would get the logs, but the link you provide (https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-getting-CodeStream-log-files) just redirects to /wiki and there is nothing about log files on that page.

**Comment by planteater** [comment] 2019-05-16 16:57
@dailytabs - Apologies for the incorrect link. Here's the correct one for grabbing the log files.

https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

Feel free to post them here, or send them to us at support@codestream.com. Thanks!

**Comment by dailytabs** [comment] 2019-05-16 19:29
[idea-logs-20190516-152755.zip](https://github.com/TeamCodeStream/CodeStream/files/3188711/idea-logs-20190516-152755.zip)

**Comment by dailytabs** [comment] 2019-05-16 19:34
IntelliJ picked up git via Cygwin:
![image](https://user-images.githubusercontent.com/1219653/57881762-1fbf5500-77f0-11e9-8ec3-10a5ad40b8ce.png)

**Comment by marcelofarias** [comment] 2019-05-16 20:23
@dailytabs is `C:\tools\cygwin\bin` included in your `%PATH%` variable (can you call `git --version` from PowerShell)?
If not, does it help if you add it and restart Windows?

**Comment by dailytabs** [comment] 2019-05-16 20:58
PS C:\Users\dwhite> git --version
    git version 2.17.0
    PS C:\Users\dwhite> Get-Command git | Select-Object -ExpandProperty Definition
    C:\tools\cygwin\bin\git.exe

**Comment by marcelofarias** [comment] 2019-05-22 16:07
@dailytabs The issue is related to the use of CodeStream with git on Cygwin. We are working on a solution for this problem.

**Comment by dailytabs** [comment] 2019-05-22 17:57
👍

**Comment by marcelofarias** [comment] 2019-06-05 13:30
Fixed on version 1.1.0+1

**Closed by marcelofarias** 2019-06-05 13:30 UTC
Labels: bug

**Comment by philzartis** [comment] 2021-03-03 17:20
Just hit this issue on cygwin git version 2.27.0 and CodeStream version "10.6.1+131".

**Comment by planteater** [comment] 2021-03-04 17:06
@philzartis - Could I trouble you for a log file? In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post it here, you can send it to me directly at support@codestream.com. Thanks!
