### ISSUE TITLE
When I open the device-ui project and add the CR task, the other project names are displayed

### ISSUE THREAD

**Issue by Callanna** [TeamCodeStream/codestream#508] opened 2021-04-19 06:52 UTC
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/14858726/115193297-8ce76d80-a11e-11eb-8bb0-e5a6c17ed4af.png">

**Comment by planteater** [comment] 2021-04-19 11:21
@Callanna - For the device-ui repo, can you do a `git remove -v` and check the remote URLs? Probably best to have your teammate check as well. Our database indicates that one of you had tuyasmart-home remote URL associated with that repo, and that's what led to it being named "tuyasmart-home" in our database. I assume that tuyasmart-home and  tuyasmart-device-ui are really two different repos?

**Comment by Callanna** [comment] 2021-04-20 02:25
"git remote -v" is right ,show 
<img width="809" alt="截屏2021-04-20 10 22 41" src="https://user-images.githubusercontent.com/14858726/115328076-9aeeca00-a1c2-11eb-8051-194fb03d162e.png">
Do you mean  "tuyasmart-home" has two repo at the same time? the next picture show same info log。
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/14858726/115328172-bc4fb600-a1c2-11eb-8200-65b0f4fcdfe4.png">

**Comment by Callanna** [comment] 2021-04-20 02:37
I teammate also show  name "tuyasmart-home" ,if the error is because of error data. how can I fix it？and How can we avoid this problem

**Comment by cstryker** [comment] 2021-04-20 13:37
@Callanna was one of those repos forked from the other, by any chance?

**Comment by cstryker** [comment] 2021-04-20 13:52
@Callanna In any case, we've separated the records for those two repos on our backend, I'm really not sure how they got "combined". That usually happens if one repo is a fork of the other, since we sometimes try to identify two repos as being the same if they have commit SHAs in common in their history. If your users reload/refresh their IDEs, you should see those repos as separate now. 

I notice in looking at your repo records in our database that you have one other repo record that may have combined two repos into one ... the two remotes are `registry.code.tuya-inc.top/tuyaandroid/sdk/os/home-sdk-sweeper` and `registry.code.tuya-inc.top/tuyaandroid/sdk/os/home-sdk-user`. Would you like me to separate those out as well?

**Comment by Callanna** [comment] 2021-04-21 03:38
> @Callanna was one of those repos forked from the other, by any chance?
no ,the two repos  always separate.

**Comment by Callanna** [comment] 2021-04-21 03:41
we use ourself server url ,  can you get the Data?or update DataBase?
<img width="814" alt="截屏2021-04-21 11 15 31" src="https://user-images.githubusercontent.com/14858726/115493471-6a786000-a296-11eb-88dd-f150a54e4ed5.png">

**Comment by Callanna** [comment] 2021-04-21 03:42
we use ourself server url , can you get the Data?or update DataBase?
<img width="1084" alt="截屏2021-04-21 11 39 28" src="https://user-images.githubusercontent.com/14858726/115493625-a4e1fd00-a296-11eb-9a05-92a33863bfcb.png">

**Comment by Callanna** [comment] 2021-04-21 03:50
> @Callanna In any case, we've separated the records for those two repos on our backend, I'm really not sure how they got "combined". That usually happens if one repo is a fork of the other, since we sometimes try to identify two repos as being the same if they have commit SHAs in common in their history. If your users reload/refresh their IDEs, you should see those repos as separate now.
> 
> I notice in looking at your repo records in our database that you have one other repo record that may have combined two repos into one ... the two remotes are `registry.code.tuya-inc.top/tuyaandroid/sdk/os/home-sdk-sweeper` and `registry.code.tuya-inc.top/tuyaandroid/sdk/os/home-sdk-user`. Would you like me to separate those out as well?

Doesn't seem to have changed，   other repo record that may have combined two repos ，What might be the cause of this problem? Can it be fixed? So we don't have to face this kind of problem in the future

**Comment by planteater** [comment] 2021-04-21 11:23
@Callanna - apologies but we did not realize that you were running CodeStream on prem. Apparently you had created a team in our cloud service at some point and that is where we had fixed the data. We’re going to need to get a look at your data and provide you with a script to fix it. I’ll follow up with instructions shortly. 

To answer your question though, this bad-data situation usually happens when someone has an incorrect remote URL configured for a repo. Or potentially if you have two repos abs one is a fork of another. I m one that you confirmed that your remotes were correct for this repo, but you’ll probably need everyone else on the team to check as well.

**Comment by planteater** [comment] 2021-04-21 13:47
Can you run the following on your CodeStream server:

```
cd ~/.codestream
docker run --rm --network=host mongo:3.4.9 mongodump --uri mongodb://localhost/codestream -c repos --archive --gzip | cat >repos.gz
```

That will create the file ~/.codestream/repos.gz which you can either post here or email to me at support@codestream.com. Thanks!

**Comment by planteater** [comment] 2021-04-26 12:09
@Callanna - Just wanted to follow up to see if we could get that dump of your repos collection so that we can get things fixed up for you. Thanks!

**Comment by planteater** [comment] 2021-05-02 17:29
@Callanna - I'm going to go ahead and close this issue out, but if you want us to help fix the issue go ahead and send that dump of your repos collection to suppor@codestream.com and we'll get you a little script to fix things up. Super easy.

**Closed by planteater** 2021-05-02 17:29 UTC
