### ISSUE TITLE
IntelliJ IDEA: Webview Login doesn't load

### ISSUE THREAD

**Issue by vansari** [TeamCodeStream/CodeStream#170] opened 2020-04-17 06:43 UTC
Hi everyone,

I have installed the plugin and set all necessary options in the Plugin Setting. But if I open the toolbar for CodeStream I can see only an infinity "loading..." message.
I have checked the Log Files and set the log level to trace. It seams that the plugin could not open the stream?! But why?!
I have reinstalled the Plugin and I got the same issue again.

**System Info (please complete the following information):**
- IDE: IntelliJ IDEA (build #IU-201.6668.121, 08 Apr 2020 16:17) 
- OS: Mac OS X (10.15.4, x86_64) 
- JRE: 11.0.6+8-b765.25 (JetBrains s.r.o) 
- JVM: 11.0.6+8-b765.25 (OpenJDK 64-Bit Server VM) 
- Plugin to blame: CodeStream version: 7.0.2+45 

**Log Files**
[IntelliJ_IDEA_Codestream.log](https://github.com/TeamCodeStream/CodeStream/files/4491300/IntelliJ_IDEA_Codestream.log)

**Comment by marcelofarias** [comment] 2020-04-17 13:13
Hi @vansari, thanks for the report.

Could you please send us the entire log to support@codestream.com?

Thanks

**Comment by vansari** [comment] 2020-04-18 12:43
Hi @marcelofarias 

email was send. I hope the information helps to solve the Problem.

Thanks

**Comment by planteater** [comment] 2020-04-28 23:26
@vansari - This should be fixed in v7.2 of our extension which was just released.

**Closed by planteater** 2020-04-28 23:26 UTC
Labels: bug

**Comment by anderssv** [comment] 2021-12-02 13:57
Seems to be issue on latest IDEA (2021.3), just installed newest version from Plugin repo. Reported error through IDEA bugreports.

**Comment by planteater** [comment] 2021-12-03 20:21
@anderssv - I haven't been able to reproduce that issue. Could I trouble you for a log file? You can send it to me at support@codestream.com. In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. Thanks!
