### ISSUE TITLE
Repo not found in your editor after upgrade to 14.6.0+272 

### ISSUE THREAD

**Issue by MiaShopgal** [TeamCodeStream/codestream#1260] opened 2022-11-11 04:24 UTC
- IDE Version:Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.12+7-b1504.27 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false

Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.9)
    manjaro.mpb (1.7)
    Gitflow-Fix (0.7.10)
    com.codestream.jetbrains-codestream (14.6.0+272)

- OS Version: macOS Ventura 13.0.1

Steps to Reproduce:

1. upgrade to 14.6.0+272
2. open CodeStream 
3. see warning : 

> Repo my1stRepoName not found in your editor. Open it, or clone the repo.
Changes can be viewed under  Diff Hunks view.

This pull request is associated with:
https://gitlab.mydomain.com/path/my1stRepoName
You have the following repositories open:
my1stRepoName
https://gitlab.mydomain.com/path/my1stRepoName
my2ndRepoName
https://gitlab.mydomain.com/path/my2ndRepoName

**Comment by MiaShopgal** [comment] 2022-11-11 04:35
no Diff Hunks view in sight

**Comment by MiaShopgal** [comment] 2022-11-11 04:39
I just check with my colleague, he didn't use submodules but get the same warning

**Comment by MiaShopgal** [comment] 2022-11-11 04:41
GitLab Community Edition [13.8.8]

**Comment by Mastertrap21** [comment] 2022-11-11 08:15
I have the exact same issue with:
GitLab 15.4.2-ee
PhpStorm 2022.2.3
Ubuntu 22.04.1 LTS

Any solutions?

**Comment by planteater** [comment] 2022-11-11 12:24
@MiaShopgal @Mastertrap21 thanks for the report. We’ll dig into this asap. I think log files will help though. Do you mind grabbing a log file per the instructions below and sending it to me at codestream@newrelic.com?

https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs

**Comment by towfiles** [comment] 2022-11-15 16:27
any update on this? i am having the same issue. i was enjoying the features of codestream for some few days now until this broke

**Comment by planteater** [comment] 2022-11-15 16:43
@towfiles - We've got a fix for this going out later this afternoon. I'll update you here as soon as it's available.

**Comment by towfiles** [comment] 2022-11-15 16:53
@planteater thanks!. I look forward

**Comment by sohan-dutta** [comment] 2022-11-16 06:00
Fixed in the latest version.
Thanks @planteater

**Comment by MiaShopgal** [comment] 2022-11-16 06:29
> Fixed in the latest version. Thanks @planteater

@sohan-dutta 
Where's the latest version?

I check the markekt place the version is 14.6.0+272

https://plugins.jetbrains.com/plugin/12206-new-relic-codestream-github-gitlab-prs-and-code-review

**Comment by david-pivonka** [comment] 2022-11-16 08:21
Thanks for the fix! The problem is I cannot find the newly released version, the latest released on Jetbrains Marketplace is 14.6.0+272.
![CleanShot 2022-11-16 at 09 20 24@2x](https://user-images.githubusercontent.com/4690621/202126293-99b4f4ef-10c3-4409-8793-b045b1aa36bd.png)

**Comment by towfiles** [comment] 2022-11-16 08:28
i was able to update it from intellij IDE directly

**Comment by MiaShopgal** [comment] 2022-11-16 09:23
It's not working... 😢 
![image](https://user-images.githubusercontent.com/2044967/202140684-baa713ba-6f91-4768-ab4c-e07935cb8bcf.png)

when I click on **PR Details** it shows...

![image](https://user-images.githubusercontent.com/2044967/202140966-9194e629-f915-476f-9737-6904f1bc329e.png)

full text :
Error Loading Merge Request:
Internal server error: {"response":{"errors":[{"message":"Internal server error"}],"status":500,"headers":{}},"request":{"query":"fragment discussionFragment on Discussion { createdAt id notes { nodes { author { name login: username avatarUrl } body bodyHtml createdAt discussion { id replyId createdAt } id position { x y newLine newPath oldLine oldPath filePath diffRefs { baseSha headSha startSha } } project { name } resolvable resolved resolvedAt resolvedBy { login: username avatarUrl } system systemNoteIconName updatedAt userPermissions { adminNote readNote resolveNote awardEmoji createNote } } } replyId resolvable resolved resolvedAt resolvedBy { login: username avatarUrl }}query GetPullRequest($fullPath: ID!, $iid: String!, $after: String) { project(fullPath: $fullPath) { name mergeRequestsEnabled mergeRequestsFfOnlyEnabled removeSourceBranchAfterMerge mergeRequest(iid: $iid) { approvedBy(first: 50) { nodes { avatarUrl name login: username } } id iid createdAt conflicts sourceBranch targetBranch title description webUrl state mergedAt reference projectId mergeWhenPipelineSucceeds mergeableDiscussionsState author { name login: username avatarUrl } diffRefs { baseSha headSha startSha } commitCount project { name path webUrl fullPath } sourceProject { name path webUrl fullPath } upvotes downvotes milestone { title id webPath dueDate } subscribed userDiscussionsCount discussionLocked forceRemoveSourceBranch reviewers { nodes { id name login: username avatarUrl } } timeEstimate totalTimeSpent updatedAt userPermissions { adminMergeRequest canMerge } discussions(first: 50, after: $after) { pageInfo { endCursor hasNextPage } nodes { ...discussionFragment } } } }}","variables":{"fullPath":"App55688/AndroidTaiwanTaxi55688","iid":"154"}}}

**Comment by david-pivonka** [comment] 2022-11-16 10:05
I updated to the latest version and the problem still occurs. It says that repo not found in editor, but when I click to show more details, it displays two identical URLs, see:
![CleanShot 2022-11-16 at 11 03 16@2x](https://user-images.githubusercontent.com/4690621/202150925-91b00f37-3dba-4516-a267-734fa5ec1b27.png)

**Comment by planteater** [comment] 2022-11-16 14:33
@david-pivonka - Did you restart your IDE after installing the update? Our telemetry shows your most recent activity still using v14.6.

**Comment by MiaShopgal** [comment] 2022-11-17 02:33
> It works for me now, thanks @sohan-dutta @planteater @MiaShopgal Did you restart JetBrains IDE (Android Studio or whatever it is) after update? That's what made it work for me.

I do, I do..

**Comment by MiaShopgal** [comment] 2022-11-17 02:35
> @MiaShopgal @Mastertrap21 thanks for the report. We’ll dig into this asap. I think log files will help though. Do you mind grabbing a log file per the instructions below and sending it to me at [codestream@newrelic.com](mailto:codestream@newrelic.com)?
> 
> https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs

I sent the logs regards of https://github.com/TeamCodeStream/codestream/issues/1260#issuecomment-1316665411

wish it could help you to find some clue, finger crossed

**Comment by MiaShopgal** [comment] 2022-11-18 04:43
> It's not working... 😢 ![image](https://user-images.githubusercontent.com/2044967/202141430-68f79d5d-2bb5-420a-a69d-8520b2b4c433.png)
> 
> when I click on **PR Details** it shows...
> 
> ![image](https://user-images.githubusercontent.com/2044967/202140966-9194e629-f915-476f-9737-6904f1bc329e.png)
> 
> full text : Error Loading Merge Request: Internal server error: {"response":{"errors":[{"message":"Internal server error"}],"status":500,"headers":{}},"request":{"query":"fragment discussionFragment on Discussion { createdAt id notes { nodes { author { name login: username avatarUrl } body bodyHtml createdAt discussion { id replyId createdAt } id position { x y newLine newPath oldLine oldPath filePath diffRefs { baseSha headSha startSha } } project { name } resolvable resolved resolvedAt resolvedBy { login: username avatarUrl } system systemNoteIconName updatedAt userPermissions { adminNote readNote resolveNote awardEmoji createNote } } } replyId resolvable resolved resolvedAt resolvedBy { login: username avatarUrl }}query GetPullRequest($fullPath: ID!, $iid: String!, $after: String) { project(fullPath: $fullPath) { name mergeRequestsEnabled mergeRequestsFfOnlyEnabled removeSourceBranchAfterMerge mergeRequest(iid: $iid) { approvedBy(first: 50) { nodes { avatarUrl name login: username } } id iid createdAt conflicts sourceBranch targetBranch title description webUrl state mergedAt reference projectId mergeWhenPipelineSucceeds mergeableDiscussionsState author { name login: username avatarUrl } diffRefs { baseSha headSha startSha } commitCount project { name path webUrl fullPath } sourceProject { name path webUrl fullPath } upvotes downvotes milestone { title id webPath dueDate } subscribed userDiscussionsCount discussionLocked forceRemoveSourceBranch reviewers { nodes { id name login: username avatarUrl } } timeEstimate totalTimeSpent updatedAt userPermissions { adminMergeRequest canMerge } discussions(first: 50, after: $after) { pageInfo { endCursor hasNextPage } nodes { ...discussionFragment } } } }}","variables":{"fullPath":"App55688/AndroidTaiwanTaxi55688","iid":"154"}}}

@planteater shoule I create another issue regards of this?

**Comment by planteater** [comment] 2022-11-18 13:46
@MiaShopgal - Since we've got a line of communication going via our support line I'll go ahead and close this, and then follow up with you directly when we have your issue fixed.

**Closed by planteater** 2022-11-18 13:46 UTC
