### ISSUE TITLE
Blank lines not preserved in posts

### ISSUE THREAD

**Issue by kingdaro** [TeamCodeStream/CodeStream#61] opened 2019-05-21 18:14 UTC
The first time trying to make a code comment, the white space gets erased. The second time, it gets preserved, but doesn't appear to render correctly.

See this video: https://streamable.com/o7zpb

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 1.0.1
 - OS + version: OS X Mojave
 - IDE + version: VS Code 1.34.0

**Log Files**
https://gist.github.com/kingdaro/4883bc23aedd4034d9944a129a314511

**Comment by planteater** [comment] 2019-05-22 21:08
@kingdaro - This issue has mostly, but not completely, been resolved in v1.0.2 of the extension that was just released. After you edit the post you'll no longer see html appear, and line breaks are preserved. The open part of the issue is that we're still not preserving blank lines in the post.

**Comment by planteater** [comment] 2019-10-22 15:05
Apologies for not updating this, but the issue was fixed a couple of months ago.

**Closed by planteater** 2019-10-22 15:05 UTC
Labels: bug
