### ISSUE TITLE
Cannot add codemarks to files with .e2e.ts

### ISSUE THREAD

**Issue by jbiskur** [TeamCodeStream/codestream#422] opened 2021-03-04 15:42 UTC
It seems not to be possible to add code marks in files with the ending .e2e.ts for example. if I remove the number from the file name it works.

This is using Webstorm and the Code Stream plugin. 

The error I receive is "There was an error creating the codemark." nothing more and nothing less

**Comment by planteater** [comment] 2021-03-04 21:40
Thanks for the report @jbiskur! Could I trouble you to send a log file? Reproduce the issue and then go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post it here, you can send it to me directly at support@codestream.com. Thanks!

**Comment by jbiskur** [comment] 2021-03-05 08:34
I have submitted the logs to the email provided

**Comment by planteater** [comment] 2021-03-16 17:09
@jbiskur - If you close the file in question, and then reopen it, does that fix the issue?

**Comment by jbiskur** [comment] 2021-03-18 17:40
> @jbiskur - If you close the file in question, and then reopen it, does that fix the issue?

no, it does not

**Comment by marcelofarias** [comment] 2021-03-18 20:47
Hi @jbiskur. Based on the logs provided, we suspect the issue is related to file renaming, and not to the file extension. CodeStream currently does not support automatic relocation of Codemarks when files are renamed, although you can still manually reposition them.

That being said, once the renamed file is committed (supposing that's the case), are you then able to create new Codemarks on it?

**Closed** 2023-09-07 23:43 UTC
